### ISSUE TITLE
Support for multiple file extensions with -ext

### ISSUE THREAD

**Issue by Paradox** [woelper/partun#6]
I haven't tested it, but, if it's not supported, I'd like to request it, if it is, I can't find anything that tells me how to do it.

**Comment by woelper** [comment]
Hi! So you are saying you did not test it, but if it does not work, you'd like it to work? :)

If you want to use this tool on zip archives which do not end in `.zip`, this should work. There is no flag or anything required - just run `partun archive.ext --list` for example. Feel free to reopen this with a better description of what you want if this is not what your feature request was aiming for.

**Comment by Paradox** [comment]
I can't believe I have to explain your own program to you, when you extract or list files in a zip file, you use -ext md, for example, to extract or list files named *.md, I'd like to be able to also extract *.bin, can this currently be done, -ext md, bin or something, and, if not, can it be added?

**Comment by Paradox** [comment]
Just for clarity I have tested the program I've used it quite a bit what I haven't tested is trying to extract or list multiple file types from within the zip file

**Comment by woelper** [comment]
> I can't believe I have to explain your own program to you (...)

That is entirely possible, as some authors like me work on multiple projects - also the tool has a bunch of options and I had no idea exactly what you wanted to achieve. In general when you submit bugs or feature requests it is a good practice to list the following:

- What is it that you are trying to achieve? (With context)
- What have you tried?
- What went wrong?

I am guessing you want -ext to display multiple extensions which match a given list, or stack multiple -ext parameters, such as 
`partun <archive> -ext jpg -ext bmp`
or `partun <archive> -ext jpg,bmp`?

**Comment by Paradox** [comment]
Yes

**Comment by Paradox** [comment]
I have now had the chance to test, and, no, it doesn't work --ext md bin obviously, doesn't work --ext md,bin doesn't work, and, neither does --ext md --ext bin

**Comment by woelper** [comment]
This should be added in the latest release. Please feel free to reopen if this does not work as expected. Please see readme for more details.

**Comment by Paradox** [comment]
This works, perfectly, thank you.
